### ISSUE TITLE
StrictDict.loads fail 

### ISSUE THREAD

**Issue by zaabjuda** [PushAMP/strictdict3#1]
> > > message_body
> > > b'\x81\xa5rules\x91\x85\xaddefault_limit\x14\xa8url_mask\x90\xabplatform_id\x01\xafplatform_prefix\xa5lenta\xa6limits\x92\x85\xa5limit\x18\xb0device_os_prefix\xa3win\xb2device_type_prefix\xa5table\xacdevice_os_id\x01\xaedevice_type_id\x02\x85\xa5limit"\xb0device_os_prefix\xa4andr\xb2device_type_prefix\xa5mobil\xacdevice_os_id\x02\xaedevice_type_id\x03'
> > > PlatformsRules.loads(message_body, msg_pack=True)
> > > Traceback (most recent call last):
> > >   File "/home/dzhiltsov/bin/pycharm-community-4.5.4/helpers/pydev/pydevd_exec2.py", line 3, in Exec
> > >     exec(exp, global_vars, local_vars)
> > >   File "<input>", line 1, in <module>
> > >   File "/home/dzhiltsov/Development/envs/payroll/lib/python3.4/site-packages/strictdict/strictbase/strictdict.py", line 39, in **repr**
> > >     return self.to_string()
> > >   File "/home/dzhiltsov/Development/envs/payroll/lib/python3.4/site-packages/strictdict/strictbase/strictdict.py", line 208, in to_string
> > >     return self.dumps(self, msg_pack=msg_pack)
> > >   File "/home/dzhiltsov/Development/envs/payroll/lib/python3.4/site-packages/strictdict/strictbase/strictdict.py", line 220, in dumps
> > >     return json.dumps(data, **kw)
> > >   File "/usr/lib/python3.4/json/**init**.py", line 230, in dumps
> > >     return _default_encoder.encode(obj)
> > >   File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
> > >     chunks = self.iterencode(o, _one_shot=True)
> > >   File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
> > >     return _iterencode(o, 0)
> > > TypeError: keys must be a string

**Comment by zaabjuda** [comment]
if data is bytes msgpack serialize str like bytes.
need fix in loads method like eg
data = msgpack.loads(data_str, encoding='utf-8')
